# Generated by Django 5.1.2 on 2024-10-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RandomModel",
        ),
        migrations.DeleteModel(
            name="SimpleModel",
        ),
    ]
