# Generated by Django 5.1.2 on 2024-10-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
