# Generated by Django 5.1.2 on 2024-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_order_orderitem_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
