name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.0]  

    services:
      mysql:
        image: mysql:8.0  
        env:
          MYSQL_ROOT_PASSWORD: pass123
          MYSQL_DATABASE: github_actions  
        ports:
          - '3306:3306'
        options: >-
          --health-cmd='mysqladmin ping -h 127.0.0.1 -u root -ppass123'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in $(seq 1 30); do
          if echo "SELECT 1;" | mysql -h 127.0.0.1 -u root -ppass123 github_actions; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DATABASE_URL: mysql://root:pass123@127.0.0.1:3306/github_actions  

    - name: Run Tests
      run: |
        python manage.py test royal
      env: 
        DATABASE_URL: mysql://root:pass123@127.0.0.1:3306/github_actions  
